### PR TITLE
Add get_logger and logging level

### PR DESCRIPTION
**Pull request by jesusbv**
Add tests for update logger level

### CODE REVIEW

**Review by KeithMnemonic — COMMENTED** [review]
The current config do not have a log value yet.  

```
 cat config.yaml
version: 1
billing_interval: hourly
query_interval: 60
product_code: br39i474i9dxutw9dgemvijnq
usage_metrics:
  managed_node_count:
    usage_aggregation: average
    consumption_reporting: volume
    minimum_consumption: 5
    dimensions:
      - dimension: tier_1
        min: 0
        max: 10
      - dimension: tier_2
        min: 11
        max: 50
      - dimension: tier_3
        min: 51
        max: 100
      - dimension: tier_4
        min: 101
        max: 250
      - dimension: tier_5
        min: 251
        max: 1000
      - dimension: tier_6
        min: 1001
reporting_api_is_cumulative: false
reporting_interval: 300
```

should we add a test to ensure this scenario is also tested.

**Review by smarlowucf — APPROVED** [review]

**Comment by smarlowucf** [comment]
> should we add a test to ensure this scenario is also tested.

Agree, would probably be good to cover this to prevent regression.

**Comment by jesusbv** [comment]
> > should we add a test to ensure this scenario is also tested.
> 
> Agree, would probably be good to cover this to prevent regression.

@KeithMnemonic , if you are referring to test that the config file includes the 
`logging` section for testing the level, that test is included in `test_adapter`
`def test_update_logger_from_config():` 
if the test should be general, I did not include that as IMHO that should be a different PR

**Comment by KeithMnemonic** [comment]
Sean and I are suggesting "a test that the config file DOES NOT include the
logging section" as that is how the files are currently distributed, without a section.

**Comment by jesusbv** [comment]
> Sean and I are suggesting "a test that the config file DOES NOT include the logging section" as that is how the files are currently distributed, without a section.

a test (that the config file DOES NOT include the logging section) for the update logger level or a different test ?

**Comment by jesusbv** [comment]
> > Sean and I are suggesting "a test that the config file DOES NOT include the logging section" as that is how the files are currently distributed, without a section.
> 
> a test (that the config file DOES NOT include the logging section) for the update logger level or a different test ? I understand you mean a different one to check the section does not exist

To be explicit, there is a test on this PR for a config file without logging section [here](https://github.com/SUSE-Enceladus/csp-billing-adapter/pull/126/files#diff-74cf4e1e504f44aa2be5ffd6e9c118d75a86dccd17fd90b81186c9a82e0b1549R88)
so, I was confused and I understand you meant/mean a different test

**Comment by KeithMnemonic** [comment]
> > > Sean and I are suggesting "a test that the config file DOES NOT include the logging section" as that is how the files are currently distributed, without a section.
> > 
> > 
> > a test (that the config file DOES NOT include the logging section) for the update logger level or a different test ? I understand you mean a different one to check the section does not exist
> 
> To be explicit, there is a test on this PR for a config file without logging section [here](https://github.com/SUSE-Enceladus/csp-billing-adapter/pull/126/files#diff-74cf4e1e504f44aa2be5ffd6e9c118d75a86dccd17fd90b81186c9a82e0b1549R88) so, I was confused and I understand you meant/mean a different test

I see. My confusion is you call  `update_logger_from_config` two times in this test function once with a config and once without.  I think the confusion is the function itself (and corresponding test) is called  'update_logger_from_config' but really there may not be an entry in config.  Maybe a better option is just "update_logger_settings" or ""update_logger_config""something that does not imply it is only getting the values from config. As when that section is missing in the config, it gets default values.

Thankyou  for clearing up my confusion.

**Review by KeithMnemonic — APPROVED** [review]
LGTM

**Review by rjschwei — APPROVED** [review]

**Pull request merged**
