### PR TITLE
Handle multiple errors using error list

### PR DESCRIPTION
**Pull request by smarlowucf**
- Use cache and csp_config in memory
- Pass in now timestamp instead of re-generating
- Save config map and cache once at end of loop

### CODE REVIEW

**Comment by smarlowucf** [comment]
This fixes #70  and #82 :

csp_config and cache are used from memory and stay in scope. At the end of each loop each is saved to datestore. This minimizes the number of failure points. It also provides a fallback mechanism if the adapter cannot perform a save due to a network blip no data is lost.

The final piece for #81 will be a separate PR.

**Comment by smarlowucf** [comment]
This also moves the timestamp update in csp_config to main event loop from the billing function. The timestamp is set on each run whether or not billing occurs.

**Review by rtamalin — APPROVED** [review]
LGTM

**Review by brett060102 — APPROVED** [review]
LGTM

**Pull request merged**
